/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.controller;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    ArrayList<Integer> inredientsids=new ArrayList();
    controller c=new controller();
    public Manager() {
        initComponents();
        setExtendedState(Manager.NORMAL);
        setDefaultCloseOperation(Manager.DISPOSE_ON_CLOSE);
        imagelabel.setHorizontalAlignment(SwingConstants.CENTER);
        imagelabel.setVerticalAlignment(SwingConstants.CENTER);
        imagelabel.setOpaque(true);
        setLocationRelativeTo(null);
        setSize(1050, 500);
        imagelabel.setPreferredSize(new java.awt.Dimension(400, 300));
        String [] header={"ID","NAME","POSITION","SALARY"};
       emptable.setModel(new DefaultTableModel(c.filltableEmp(),header));
       empid.removeAllItems();
       String[] ids=c.fillcomboyid();
        for (int i = 0; i < ids.length; i++) {
            empid.addItem(ids[i]);
        }
        itemcombo.removeAllItems();
         String[] combo=c.fillcomboynameofitem();
        for (int i = 0; i < combo.length; i++) {
            itemcombo.addItem(combo[i]);
        }
        storecombo.removeAllItems();
        String []ingre=c.fillcombobyStoreingre();
        for (int i = 0; i < ingre.length; i++) {
            storecombo.addItem(ingre[i]);
        }
        createpanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        itempanel = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        itemcombo = new javax.swing.JComboBox<>();
        itemname = new javax.swing.JTextField();
        itemprice = new javax.swing.JTextField();
        label6 = new java.awt.Label();
        radiof = new javax.swing.JRadioButton();
        radiod = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        label = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        createpanel = new javax.swing.JPanel();
        storecombo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        staffpanel = new javax.swing.JPanel();
        addStaff = new javax.swing.JButton();
        RemoveStaff = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        emptable = new javax.swing.JTable();
        salary = new javax.swing.JTextField();
        label9 = new java.awt.Label();
        empid = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2081, 20, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2456, 6, -1, -1));

        itempanel.setBackground(new java.awt.Color(0, 0, 0));
        itempanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Remove item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        itempanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, 36));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add Item");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        itempanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 100, 36));

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Item Name");
        itempanel.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Item Price");
        itempanel.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, -1, -1));

        itemcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcomboActionPerformed(evt);
            }
        });
        itempanel.add(itemcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 271, 130, 30));
        itempanel.add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 16, 189, -1));
        itempanel.add(itemprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 70, 189, -1));

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Item type");
        itempanel.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 119, -1));

        radiof.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radiof);
        radiof.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radiof.setForeground(new java.awt.Color(255, 255, 255));
        radiof.setText("food");
        itempanel.add(radiof, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 131, 59, -1));

        radiod.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(radiod);
        radiod.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radiod.setForeground(new java.awt.Color(255, 255, 255));
        radiod.setText("drink");
        itempanel.add(radiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 131, 80, -1));

        des.setColumns(20);
        des.setRows(5);
        jScrollPane2.setViewportView(des);

        itempanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, 145));

        label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("The description of");
        itempanel.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Delete des");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        itempanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 100, 33));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Store");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        itempanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 90, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        itempanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Show des");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        itempanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, 30));

        createpanel.setBackground(new java.awt.Color(0, 0, 0));

        storecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        storecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storecomboActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("ADD ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SUBMIT DESCRIPTION");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createpanelLayout = new javax.swing.GroupLayout(createpanel);
        createpanel.setLayout(createpanelLayout);
        createpanelLayout.setHorizontalGroup(
            createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createpanelLayout.createSequentialGroup()
                        .addComponent(storecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        createpanelLayout.setVerticalGroup(
            createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createpanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(createpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        itempanel.add(createpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 220, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Add des for item");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        itempanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("CHECK ORDERS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        itempanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 140, 40));

        getContentPane().add(itempanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 510, 450));

        staffpanel.setBackground(new java.awt.Color(0, 0, 0));
        staffpanel.setForeground(new java.awt.Color(255, 255, 255));
        staffpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addStaff.setBackground(new java.awt.Color(0, 0, 0));
        addStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addStaff.setForeground(new java.awt.Color(255, 255, 255));
        addStaff.setText("Add emp");
        addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffActionPerformed(evt);
            }
        });
        staffpanel.add(addStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 204, 123, 36));

        RemoveStaff.setBackground(new java.awt.Color(0, 0, 0));
        RemoveStaff.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveStaff.setForeground(new java.awt.Color(255, 255, 255));
        RemoveStaff.setText("Remove emp");
        RemoveStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveStaffActionPerformed(evt);
            }
        });
        staffpanel.add(RemoveStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 204, 123, 36));

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Employee id:");
        staffpanel.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 110, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("NAME:");
        staffpanel.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("POSITION:");
        staffpanel.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 111, -1, -1));
        staffpanel.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 16, 188, -1));
        staffpanel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 60, 188, -1));
        staffpanel.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 110, 188, -1));

        emptable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        emptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        emptable.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane3.setViewportView(emptable);

        staffpanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, 440, 240));
        staffpanel.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 170, 188, -1));

        label9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("SALARY:");
        staffpanel.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 164, -1, -1));

        empid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        staffpanel.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 211, 90, -1));

        getContentPane().add(staffpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 500));

        imagelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Restaurant-Logo-Designs.jpg"))); // NOI18N
        imagelabel.setText("jLabel2");
        getContentPane().add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffActionPerformed
       int ids=Integer.parseInt(id.getText());
       String empname=name.getText();
       String emppos=role.getText();
       double empsalary=Double.parseDouble(salary.getText());
       if(!c.checkRepitionEmpId(ids)){
            c.addemployee(ids, empname, empsalary, emppos);
       String [] header={"ID","NAME","POSITION","SALARY"};
       emptable.setModel(new DefaultTableModel(c.filltableEmp(),header));
        empid.removeAllItems();
       String[] combo=c.fillcomboyid();
        for (int i = 0; i < combo.length; i++) {
            empid.addItem(combo[i]);
        }
       id.setText("");
       name.setText("");
       role.setText("");
       salary.setText(""); 
       }else{
        JOptionPane.showMessageDialog(null, "Please use another employee id","",JOptionPane.WARNING_MESSAGE); 
       }
     
        
        
    }//GEN-LAST:event_addStaffActionPerformed

    private void RemoveStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveStaffActionPerformed
       int id=Integer.parseInt(empid.getSelectedItem().toString());
       String name=c.getempname(id);
       int res= JOptionPane.showConfirmDialog(null, "Are you sure do you want to remove "+name, "",JOptionPane.OK_CANCEL_OPTION );
     if(res==JOptionPane.OK_OPTION){
         c.removeemployee(id);
         String [] header={"ID","NAME","POSITION","SALARY"};
       emptable.setModel(new DefaultTableModel(c.filltableEmp(),header));
       String[] combo=c.fillcomboyid();
        for (int i = 0; i < combo.length; i++) {
            empid.addItem(combo[i]);
        }
       JOptionPane.showMessageDialog(null, name+" is sucessfully removed");
     
     }
       
        
    }//GEN-LAST:event_RemoveStaffActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Store s=new Store();
        s.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String name=itemcombo.getSelectedItem().toString();
        int res= JOptionPane.showConfirmDialog(null, "Are you sure do you want to remove the description of "+name, "",JOptionPane.OK_CANCEL_OPTION );
        if(res==JOptionPane.OK_OPTION){
            c.removedescriptionforItemMenu(name);
            JOptionPane.showMessageDialog(null, "The description of "+name+" is deleted");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Object o= itemcombo.getSelectedItem();
        
        if(o!=null){
        String name =itemcombo.getSelectedItem().toString();
        String it=storecombo.getSelectedItem().toString();
        String []ar=it.split("-");
        int id=Integer.parseInt(ar[0]);
        inredientsids.add(id);
        des.append(ar[1]+"\n");
        } 

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String itemname=itemcombo.getSelectedItem().toString();
        if(!c.checkDescriptionOfitemIffound(itemname)){
        if(!inredientsids.isEmpty()){
            c.addDescription(itemname, inredientsids);
            label.setText("The desription of");
            des.setText("");
            JOptionPane.showMessageDialog(null, "The description has been added");
            createpanel.setVisible(false);

        }else{
            JOptionPane.showMessageDialog(null, "no item selected to create a description","",JOptionPane.WARNING_MESSAGE);
        }
         }else{
            JOptionPane.showMessageDialog(null, "A desription is already added to this item ","",JOptionPane.WARNING_MESSAGE); 
         }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void storecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storecomboActionPerformed
        
    }//GEN-LAST:event_storecomboActionPerformed

    private void itemcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcomboActionPerformed
        des.setText("");
        inredientsids.clear();
        label.setText("The desription of");

    }//GEN-LAST:event_itemcomboActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String name=itemname.getText();
        String type="";
        if(radiof.isSelected()){
            type="food";
        }else if(radiod.isSelected()){
            type="drink";
        }
        double price = Double.parseDouble(itemprice.getText());
        if(!c.checkRepitionnameInMneu(name)){
           c.addItemMenu(name, type, price);
        itemname.setText("");
        buttonGroup1.clearSelection();
        itemprice.setText("");
        itemcombo.removeAllItems();
        String[] combo=c.fillcomboynameofitem();
        for (int i = 0; i < combo.length; i++) {
            itemcombo.addItem(combo[i]);
        }  
        }else{
             JOptionPane.showMessageDialog(null, "This name is already in our menu please enter another name","",JOptionPane.WARNING_MESSAGE);
        }
       

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name=itemcombo.getSelectedItem().toString();
        int res= JOptionPane.showConfirmDialog(null, "Are you sure do you want TO remove the item menu "+name, "",JOptionPane.OK_CANCEL_OPTION );
        if(res==JOptionPane.OK_OPTION){
            c.removeItemmenu(name);
            itemcombo.removeAllItems();
            String[] combo=c.fillcomboynameofitem();
            for (int i = 0; i < combo.length; i++) {
                itemcombo.addItem(combo[i]);
            }
            JOptionPane.showMessageDialog(null, "this item is sucessffuly removed");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String name=itemcombo.getSelectedItem().toString();
        if(c.checkDescriptionOfitemIffound(name)){
            label.setText("The description of "+name+" is:");
            des.setText(c.showdescription(name)); 
        }else{
             JOptionPane.showMessageDialog(null, "No description added to this item");
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          String name=itemcombo.getSelectedItem().toString();
        if(!c.checkDescriptionOfitemIffound(name)){
            label.setText("The description of "+name+" is:");
           createpanel.setVisible(true);  
         } else{
            JOptionPane.showMessageDialog(null, "A desription is already added to this item ","",JOptionPane.WARNING_MESSAGE); 
         }       
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       CheckOrdersANDReservation check=new CheckOrdersANDReservation();
       check.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RemoveStaff;
    private javax.swing.JButton addStaff;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel createpanel;
    private javax.swing.JTextArea des;
    private javax.swing.JComboBox<String> empid;
    private javax.swing.JTable emptable;
    private javax.swing.JTextField id;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JComboBox<String> itemcombo;
    private javax.swing.JTextField itemname;
    private javax.swing.JPanel itempanel;
    private javax.swing.JTextField itemprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label9;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton radiod;
    private javax.swing.JRadioButton radiof;
    private javax.swing.JTextField role;
    private javax.swing.JTextField salary;
    private javax.swing.JPanel staffpanel;
    private javax.swing.JComboBox<String> storecombo;
    // End of variables declaration//GEN-END:variables
}
