/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controll.ReservationAndOrderControll;
import Controll.controller;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class System extends javax.swing.JFrame {

    /**
     * Creates new form System
     */
    public static ReservationAndOrderControll ro=new ReservationAndOrderControll();
    public static controller c=new controller();
    public static int num;
    public System() {
        initComponents();
        tablecombo.removeAllItems();
        editpanel.setVisible(false);
        tablecombo.setModel(new DefaultComboBoxModel(c.fillcombobytablenumbers()));
        if(ro.checkReservation()){
          String []title={"Customer name","Number of guets","Time"};
        restable.setModel(new DefaultTableModel(ro.filltablebyResevations(),title));  
        }
        String title2 []={"Table number","Nbr of seats","Status"};
         tab.setModel(new DefaultTableModel(c.filltablebyTables(),title2));
          updateDateLabel();
        startDateUpdateTimer();
        setDefaultCloseOperation(System.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
    @Override
    public void windowClosing(WindowEvent e) {
        if(!c.checktablesActivity()){
            dispose();
        }else{
          JOptionPane.showMessageDialog(null, "You still have a resereved tables you cannot exist the system"); 
        }
}

         
    });
       
     
  }

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tablecombo = new javax.swing.JComboBox<>();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        hour = new javax.swing.JComboBox<>();
        minutes = new javax.swing.JComboBox<>();
        ap = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        restable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nbrguest = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        editpanel = new javax.swing.JPanel();
        editlabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        editedvalue = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        datelabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the reservation id:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        tablecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(tablecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 100, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 110, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose the Table number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter the customer name: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        hour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        minutes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        getContentPane().add(minutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        ap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });
        getContentPane().add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Time:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Press to order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        restable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        restable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(restable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 380, 270));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add new Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Submit Reservation");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number of guests :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(nbrguest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 90, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete reservation");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        tab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 380, 260));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Edit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, 40));

        editpanel.setBackground(new java.awt.Color(0, 0, 0,80));
        editpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editlabel.setBackground(new java.awt.Color(0, 0, 0));
        editlabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editlabel.setForeground(new java.awt.Color(255, 255, 255));
        editlabel.setText("Enter the new");
        editpanel.add(editlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 260, -1));
        editpanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 190, -1));
        editpanel.add(editedvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 140, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("change");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        editpanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        getContentPane().add(editpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 440, 140));

        datelabel.setBackground(new java.awt.Color(0, 0, 0));
        datelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        datelabel.setForeground(new java.awt.Color(255, 255, 255));
        datelabel.setText("jLabel7");
        getContentPane().add(datelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Restaurant-Logo-Designs.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void updateDateLabel() {
        Date now = new Date();
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = dateFormat.format(now);
        datelabel.setText(formattedDate);
    }
    private void startDateUpdateTimer() {
        Timer timer = new Timer(1000 * 60 * 60 * 24, e -> updateDateLabel());
        timer.setInitialDelay(0);
        timer.start();
    }
    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Menuframe m=new Menuframe();
        m.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TableInfoFr tb = new TableInfoFr();
        tb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int tabnum = Integer.parseInt(tablecombo.getSelectedItem().toString());
       num=tabnum;
        if(!ro.checkRepetitionTable(tabnum)){
           Order o = new Order();
            o.setVisible(true);    
       }else{
           JOptionPane.showMessageDialog(null, "Table number "+tabnum+" is not reserved you cannot order","",JOptionPane.WARNING_MESSAGE);
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int resid=Integer.parseInt(id.getText());
        int tabnum = Integer.parseInt(tablecombo.getSelectedItem().toString());
        
        int guest=Integer.parseInt(nbrguest.getValue().toString());
        if(guest>0){
        if(!ro.checkIfOrderIsSubmited(resid)){
        if(ro.checkRerservationID(resid)){
        if(ro.checkRepetitionTable(tabnum)){
        String cusname=name.getText();
        
        String h=hour.getSelectedItem().toString();
        String m=minutes.getSelectedItem().toString();
        String p=ap.getSelectedItem().toString();
        String time = h+":"+m+" "+p;
        ro.addReservation(resid, tabnum, cusname, time, guest);
        c.setTableReserved(tabnum);
        String []title={"Customer name","Number of guets","Time"};
         restable.setModel(new DefaultTableModel(ro.filltablebyResevations(),title)); 
         String title2 []={"Table number","Nbr of seats","Status"};
         tab.setModel(new DefaultTableModel(c.filltablebyTables(),title2));
        id.setText("");
        name.setText("");
        nbrguest.setValue(0);
        }else{
            JOptionPane.showMessageDialog(null, "this table already reserved");
        }
        }else{
             JOptionPane.showMessageDialog(null, "Please use another reservation Id");
        }
             }else{
            JOptionPane.showMessageDialog(null, "Please use another reservation Id");
        }
        }else{
           JOptionPane.showMessageDialog(null, "Number of guests must be greater than 0"); 
        }
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     WelcomeFrame w= new WelcomeFrame();
     w.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int col = restable.getSelectedColumn();
         int row = restable.getSelectedRow();
         String NEW = editedvalue.getText();
         if(!NEW.isEmpty()){
              ro.EditReservation(col, NEW, row);
          String []title={"Customer name","Number of guets","Time"};
         restable.setModel(new DefaultTableModel(ro.filltablebyResevations(),title)); 
          editpanel.setVisible(false); 
            
         }else{
             JOptionPane.showMessageDialog(null, "Value not found");
            editpanel.setVisible(false); 
         }
        
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      
       if(restable.getSelectedRow()>=0){
           int row = restable.getSelectedRow();
       int resid=ro.GetResId(ro.getTablenumberfromINdex(row));
        if(!ro.checkIfOrderIsSubmited(resid)){
       
        c.setTableunReserved(ro.getTablenumberfromINdex(row));
       ro.removerreservation(row);
      String []title={"Customer name","Number of guets","Time"};
         restable.setModel(new DefaultTableModel(ro.filltablebyResevations(),title)); 
         String title2 []={"Table number","Nbr of seats","Status"};
         tab.setModel(new DefaultTableModel(c.filltablebyTables(),title2));
       }else{
           JOptionPane.showMessageDialog(null, "A order is placed in this table we cannot remove","",JOptionPane.WARNING_MESSAGE); 
        }
       }else{
         JOptionPane.showMessageDialog(null, "Please select  a row from table","",JOptionPane.WARNING_MESSAGE);   
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int col = restable.getSelectedColumn();
        if(col==0){
            editlabel.setText("Enter the new customer name:");
            editpanel.setVisible(true);
        }else if(col==1){
             editlabel.setText("Enter the new nbr of guests:");
             editpanel.setVisible(true);
        }else if(col==2){
             editlabel.setText("Enter the new time:");
             editpanel.setVisible(true);
        }else{
          JOptionPane.showMessageDialog(null, "You need to select a column");  
        }
       
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ap;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField editedvalue;
    private javax.swing.JLabel editlabel;
    private javax.swing.JPanel editpanel;
    private javax.swing.JComboBox<String> hour;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> minutes;
    private javax.swing.JTextField name;
    private javax.swing.JSpinner nbrguest;
    private javax.swing.JTable restable;
    private javax.swing.JTable tab;
    private javax.swing.JComboBox<String> tablecombo;
    // End of variables declaration//GEN-END:variables
}
